{% set name = "jaxtyping" %}
{% set version = "0.2.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxtyping-{{ version }}.tar.gz
  sha256: 83c7c0bfae1d1ce25801480b5572d96c0f2b889785b4e50bdc25a07058b7bd50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9
    - typeguard ==2.13.3

test:
  imports:
    - jaxtyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jaxtyping
  summary: Type annotations and runtime checking for shape and dtype of JAX arrays, and PyTrees.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - ngam
